defaultPlatforms:
- linux/amd64
- linux/arm64

builds:
- id: pod-monitor
  main: .
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -X main.Version={{.Env.VERSION}}
  - -X main.GitCommit={{.Env.GIT_COMMIT}}
  - -X main.BuildTime={{.Env.BUILD_TIME}}
