---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-monitor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-monitor
subjects:
- kind: ServiceAccount
  name: pod-monitor
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-monitor
  namespace: default
  labels:
    app: pod-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-monitor
  template:
    metadata:
      labels:
        app: pod-monitor
    spec:
      serviceAccountName: pod-monitor
      containers:
      - name: pod-monitor
        image: ko://github.com/pascal71/k8s-probe-monitor
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: PORT
          value: "8090"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: pod-monitor
  namespace: default
spec:
  selector:
    app: pod-monitor
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  type: NodePort
